# source https://docs.travis-ci.com/user/deployment/pages/
# source https://www.metachris.com/2017/04/continuous-deployment-hugo---travis-ci--github-pages/

addons:
  apt:
    packages:
      - python-pygments

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-ARM64.tar.gz -O hugo.tar.gz
  - tar -xvf hugo.tar.gz

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep-history: true
  fqdn: hashemian.me
  on:
    branch: gh-pages
