baseURL = "https://hashemian.me/"
languageCode = "en-us"
title = "Sajjad Hashemian"
theme = "kiera"

pygmentsUseClassic=true
pygmentsCodeFences=true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "en"
    weight = 2
  [languages.fa]
  languageCode = "fa-ir"
    contentDir = "content/fa"
    languageName = "فا"
    title = "سجاد هاشمیان"
    weight = 1
    dir = "rtl"
    [languages.fa.params]
      tagline = "کد مود اینا..."

[author]
  name = "سجاد هاشمیان"
  homepage = "https://hashemian.me/"
  github = "sijad"

[params]
  tagline = ""
