baseURL = "https://hashemian.me/"
languageCode = "fa-ir"
title = "وبلاگ من"
theme = "sofya"

[author]
  name = "سجاد هاشمیان"
  homepage = "https://hashemian.me/"

[params]
  desc = "کد مود اینا..."
  displaymenu = true
  github = "https://github.com/sijad"

[[menu.main]]
    name = "خانه"
    pre = ""
    weight = -110
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "درباره"
    pre = ""
    weight = -100
    identifier = "about"
    url = "/about/"
